// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngtvzjgvvabortrdugty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndHZ6amd2dmFib3J0cmR1Z3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjI1OTEsImV4cCI6MjA1OTAzODU5MX0.snq4WticAa0PxfaTNHP8JXrB7IF2mQislH0Xlon3JHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);